export const SET_HOME_AIRPORT = "SET_HOME_AIRPORT";
export const SET_EMAIL = "SET_EMAIL";
export const SET_PASSWORD = "SET_PASSWORD";
export const SET_FIRST_NAME = "SET_FIRST_NAME";
export const SET_LAST_NAME = "SET_LAST_NAME";
export const SET_PLAN = "SET_PLAN";
export const SET_PROMO_CODE = "SET_PROMO_CODE";
export const SET_ZIP = "SET_ZIP";
export const SET_CARD_NUMBER = "SET_CARD_NUMBER";
export const SET_EXPIRY = "SET_EXPIRY";
export const SET_CVC = "SET_CVC";
export const SET_PROMO_INVALID = "SET_PROMO_INVALID";
export const SET_PROMO_CHECK_PROGRESS = "SET_PROMO_CHECK_PROGRESS";
export const SET_DISCOUNT = "SET_DISCOUNT";
export const SET_INVITE_CODE_CHECK_PROGRESS = "SET_INVITE_CODE_CHECK_PROGRESS";
export const SET_INVITE = "SET_INVITE";
export const SET_INVITE_CODE_REJECTED = "SET_INVITE_CODE_REJECTED";
export const SET_ACTIVATION_CODE_CHECK_PROGRESS =
  "SET_ACTIVATION_CODE_CHECK_PROGRESS";
export const SET_ACTIVATION = "SET_ACTIVATION";
export const SET_ACTIVATION_CODE_REJECTED = "SET_ACTIVATION_CODE_REJECTED";

export const SET_EMAIL_EXISTS = "SET_EMAIL_EXISTS";
export const SET_EMAIL_VERIFIED = "SET_EMAIL_VERIFIED";
export const SET_FORM_ERRORS = "SET_FORM_ERRORS";
export const SET_SUBSCRIBE_REQUEST_ERROR_MESSAGE =
  "SET_SUBSCRIBE_REQUEST_ERROR_MESSAGE";
export const SET_SUBSCRIBE_REQUEST_FAILED = "SET_SUBSCRIBE_REQUEST_FAILED";
export const SET_MODE = "SET_MODE";
