export const SELECT_AIRLINE = "SELECT_AIRLINE";
export const DESELECT_AIRLINE = "DESELECT_AIRLINE";
export const TOGGLE_AIRLINE = "TOGGLE_AIRLINE";
export const SET_LOCATION_FILTER = "SET_LOCATION_FILTER";
export const RESET_FILTERS = "RESET_FILTERS";
export const SET_RANDOM_DEALS = "SET_RANDOM_DEALS";
export const SET_USER_DEALS = "SET_USER_DEALS";
export const SET_RANDOM_DEALS_RETRIEVE_ERROR =
  "SET_RANDOM_DEALS_RETRIEVE_ERROR";
export const SET_USER_DEALS_RETRIEVE_ERROR = "SET_USER_DEALS_RETRIEVE_ERROR";
export const SET_FEED_DEALS = "SET_FEED_DEALS";
export const SET_FEED_DEALS_RETRIEVE_ERROR = "SET_FEED_DEALS_RETRIEVE_ERROR";
export const RESET_DEALS = "RESET_DEALS";
