export const airlineCodes = {
  UA: "United Airlines",
  AA: "American Airlines",
  LH: "Lufthansa",
  BA: "British Airways",
  TK: "Turkish Airlines",
  DL: "Delta",
  KL: "KLM",
  AF: "Air France",
  LX: "SWISS",
  AC: "Air Canada",
  IB: "Iberia",
  OS: "Austrian Airlines",
  EK: "Emirates",
  AY: "Finnair",
  AZ: "Alitalia",
  SU: "Aeroflot",
  SK: "SAS",
  QR: "Qatar Airways",
  SN: "Brussels Airlines",
  SQ: "Singapore Airlines",
  CX: "Cathay Pacific",
  EY: "Etihad Airways",
  TP: "AIR PORTUGAL",
  LO: "LOT",
  AS: "Alaska Airlines",
  B6: "JetBlue",
  KE: "Korean Air",
  CA: "Air China",
  LA: "LATAM Airlines",
  AM: "Aeromexico",
  CZ: "China Southern",
  UX: "Air Europa",
  TG: "Thai Airways",
  NK: "Spirit Airlines",
  ET: "Ethiopian Air",
  MU: "China Eastern",
  FR: "Ryanair",
  U2: "easyJet",
  AV: "Avianca",
  F9: "Frontier",
  VY: "Vueling",
  NH: "ANA",
  EI: "Aer Lingus",
  MS: "Egypt Air",
  MH: "Malaysia Airlines",
  A3: "Aegean Airlines",
  CM: "Copa Airlines",
  DY: "Norwegian",
  EW: "Eurowings",
  JL: "Japan Airlines",
  PS: "Intl Air",
  OZ: "Asiana Airlines",
  PC: "Pegasus Airlines",
  QF: "Qantas Airways",
  BR: "EVA Air",
  JU: "Air Serbia",
  WY: "Oman Air",
  AT: "Air Maroc",
  CI: "China Airlines",
  PR: "Philippine Airlines",
  WN: "Southwest",
  AI: "Air India",
  BT: "airBaltic",
  MF: "XiamenAir",
  RJ: "Royal Jordanian",
  VN: "Vietnam Airlines",
  GF: "Gulf Air",
  WS: "WestJet",
  UL: "SriLankan Airlines",
  G3: "GOL",
  "4O": "Interjet",
  W6: "Wizz Air",
  AD: "Azul",
  FI: "Icelandair",
  OK: "Czech Airlines",
  VS: "Virgin Atlantic",
  AR: "Aerolineas Argentinas",
  RO: "TAROM",
  SY: "Country Air",
  SV: "SAUDIA",
  LY: "EL AL",
  GA: "Garuda Indonesia",
  KU: "Kuwait Airways",
  TR: "Scoot",
  OD: "Malindo Air",
  VA: "Virgin Australia",
  S7: "S7 Airlines",
  "6E": "IndiGo",
  SA: "South African",
  Y4: "Volaris",
  KQ: "Kenya Airways",
  NZ: "New Zealand",
  QS: "Smartwings",
  BI: "Brunei Airlines",
  HA: "Hawaiian Airlines",
  HU: "Hainan Airlines",
  ME: "MEA",
  OE: "Lauda",
  OU: "Croatia Airlines",
  B2: "Belavia",
  KM: "Air Malta",
  LG: "Luxair",
  PG: "Bangkok Airways",
  HX: "Kong Airlines",
  KC: "Air Astana",
  SL: "Lion Air",
  "3K": "Jetstar Asia",
  "5J": "Cebu Pacific",
  G4: "Allegiant Air",
  FZ: "flydubai",
  "3U": "Sichuan Airlines",
  UK: "Vistara",
  VB: "VivaAerobus",
  VJ: "VietJet Air",
  AH: "Air Algerie",
  AK: "AirAsia",
  TS: "Air Transat",
  BE: "Flybe",
  IG: "Air Italy",
  TU: "Tunisair",
  HV: "Transavia",
  JQ: "Jetstar",
  SG: "SpiceJet",
  TO: "Transavia France",
  G9: "Air Arabia",
  KA: "Cathay Dragon",
  FD: "Thai AirAsia",
  FJ: "Fiji Airways",
  G8: "GoAir",
  MK: "Air Mauritius",
  "0B": "Blue Air",
  "7C": "Jeju Air",
  ZH: "Shenzhen Airlines",
  FB: "Bulgaria Air",
  J9: "Jazeera Airways",
  MI: "SilkAir",
  S4: "Azores Airlines",
  D7: "AirAsia X",
  FM: "Shanghai Airlines",
  H2: "Sky Airline",
  HY: "Uzbekistan Airways",
  U6: "Ural Airlines",
  XY: "flynas",
  Z2: "Philippines AirAsia",
  DP: "Pobeda",
  ID: "Batik Air",
  NX: "Air Macau",
  PK: "International Airlines",
  D8: "Air International",
  HO: "Juneyao Airlines",
  I2: "Iberia Express",
  J2: "Azerbaijan Airlines",
  LS: "Jet2",
  SC: "Shandong Airlines",
  TN: "Tahiti Nui",
  TW: "way Air",
  UT: "UTair",
  BG: "Biman Bangladesh",
  DE: "Condor",
  FA: "FlySafair",
  I5: "AirAsia India",
  IX: "India Express",
  JE: "Mango",
  LJ: "Jin Air",
  MN: "Kulula",
  QZ: "Indonesia AirAsia",
  SS: "Corsair",
  UO: "HK Express",
  VE: "EasyFly",
  VV: "Air Peru",
  W9: "Air UK",
  WB: "RwandAir",
  WE: "THAI Smile",
  ZE: "Eastar Jet",
  "9U": "Air Moldova",
  BW: "Caribbean Airlines",
  BX: "Air Busan",
  DD: "Nok Air",
  DI: "Air UK",
  GK: "Jetstar Japan",
  JA: "JetSMART",
  MM: "Peach",
  N4: "Nordwind Airlines",
  OB: "BoA",
  P5: "Wingo",
  PD: "Porter Airlines",
  Q6: "Costa Rica",
  TT: "Tigerair Australia",
  TX: "Air Cara\u00c3\u00afbes",
  V7: "Volotea",
  XQ: "SunExpress",
  "7R": "RusLine",
  "8M": "MAI",
  B0: "La Compagnie",
  BL: "Jetstar Pacific",
  DT: "TAAG",
  F8: "Flair Airlines",
  FY: "Firefly",
  GS: "Tianjin Airlines",
  HM: "Air Seychelles",
  IT: "Tigerair Taiwan",
  JT: "Lion Air",
  LM: "Loganair",
  OV: "Salam Air",
  QG: "Citilink",
  QV: "Lao Airlines",
  RS: "Air Seoul",
  SW: "Air Namibia",
  TB: "Fly Belgium",
  "3O": "Arabia Maroc",
  UU: "Air Austral",
  "5N": "Smartavia",
  VZ: "Vietjet Air",
  WF: "Wideroe",
  X3: "TUI fly",
  WZ: "Red Wings",
  XW: "NokScoot",
  "9C": "Spring Airlines",
  A4: "AZIMUTH",
  A9: "Georgian Airways",
  AE: "Mandarin Airlines",
  B7: "UNI AIR",
  BF: "French Bee",
  BJ: "Nouvelair",
  BS: "Bangla Airlines",
  BV: "Panorama Airlines",
  CY: "Cyprus Airways",
  DG: "Cebgo",
  DN: "Air Argentina",
  EN: "Air Dolomiti",
  EQ: "TAME",
  GQ: "Sky Express",
  HC: "Air Senegal",
  IZ: "Arkia",
  JD: "Capital Airlines",
  K6: "Angkor Air",
  KP: "ASKY",
  KX: "Cayman Airways",
  LF: "Contour",
  LQ: "Lanmei Airlines",
  NF: "Air Vanuatu",
  NP: "Nile Air",
  OA: "Olympic Air",
  OM: "MIAT Mongolian",
  PA: "airblue",
  PU: "Plus Ultra",
  PX: "Air Niugini",
  QD: "JC Airlines",
  RA: "Nepal Airlines",
  RX: "Regent Airways",
  SB: "Aircalin",
  SJ: "Sriwijaya Air",
  "2I": "Star Peru",
  "2Z": "Passaredo",
  TA: "El Salvador",
  TF: "Regional Aviation",
  "3M": "Silver Airways",
  "3S": "Air Antilles",
  UB: "National Airlines",
  "4B": "Boutique Air",
  "4M": "LATAM Argentina",
  UP: "Bahamasair",
  VR: "Verde Airlines",
  VW: "Aeromar",
  WG: "Sunwing Airlines",
  "6H": "ISRAIR",
  WK: "Edelweiss Air",
  WO: "Swoop",
  XC: "Corendon",
  XJ: "AirAsia X",
  XK: "Air Corsica",
  XL: "LATAM Ecuador",
  Y7: "NordStar",
  "8L": "Lucky Air",
  YM: "Montenegro Air",
  "8Q": "Onur Air",
  ZL: "Rex",
  "9K": "Cape Air",
  "9R": "SATENA",
  "9V": "Avior Airlines",
  A2: "Astra Airlines",
  A5: "HOP!",
  A7: "Calafia Airlines",
  A8: "Uganda Limited",
  AG: "Aruba Airlines",
  AN: "Advanced Air",
  AO: "Air Juan",
  AP: "Albastar",
  AQ: "9 Air",
  B3: "Bhutan Airlines",
  B4: "ZanAir Limited",
  B5: "-SAX",
  B8: "Eritrean Airlines",
  AW: "AWA",
  B9: "Air Tours",
  BB: "Seaborne Airlines",
  BC: "Skymark Airlines",
  BK: "Okay Airways",
  BP: "Air Botswana",
  C3: "Trade Air",
  BU: "CAA",
  BZ: "BlueBird Airways",
  CC: "CM Airlines",
  CE: "Chalair Aviation",
  CG: "Airlines PNG",
  CN: "China Air",
  CQ: "Coastal",
  D2: "Severstal",
  DJ: "AirAsia Japan",
  DR: "Ruili Airlines",
  E5: "Air Arabia",
  DU: "Long Haul",
  DV: "SCAT Airlines",
  DX: "DAT",
  E9: "evelop!",
  EB: "Wamos Air",
  EG: "Ernest Airlines",
  EL: "Ellinair",
  EO: "Pegas Fly",
  EP: "Aseman Airlines",
  F3: "flyadeal",
  F4: "Air Flamenco",
  EU: "Chengdu Airlines",
  FC: "Fly Corporate",
  FE: "Air Transport",
  FG: "Ariana",
  FN: "fastjet",
  G5: "Express Airlines",
  FT: "FlyEgypt",
  FU: "Fuzhou Airlines",
  FW: "IBEX Airlines",
  GJ: "Loong Air",
  GL: "Air Greenland",
  GP: "APG Airlines",
  GR: "Aurigny Air",
  GV: "Grant Aviation",
  H9: "Himalaya Airlines",
  GX: "GX Airlines",
  GY: "Guizhou Airlines",
  GZ: "Air Rarotonga",
  HD: "Air Do",
  HF: "C\u00c3\u00b4te d\u00e2\u0080\u0099Ivoire",
  I8: "Izhavia",
  HZ: "Aurora Airlines",
  IA: "Iraqi Airways",
  IE: "Solomon Airlines",
  IF: "Fly Baghdad",
  IJ: "Airlines Japan",
  IK: "Air Kiribati",
  IL: "Trigana Air",
  IN: "NAM Air",
  IO: "IrAero",
  IQ: "Qazaq Air",
  J3: "Northwestern Air",
  IS: "Sepehran Airlines",
  J4: "Badr Airlines",
  J5: "Alaska Seaplanes",
  J7: "Afrijet",
  IW: "Wings Air",
  JC: "Air Commuter",
  JH: "Dream Airlines",
  JJ: "Airlines Brasil",
  JM: "Jambojet",
  JR: "Joy Air",
  K3: "Air Company",
  JV: "Bearskin Airlines",
  K7: "Air KBZ",
  JY: "interCaribbean Airways",
  KB: "Drukair",
  KF: "Air Belgium",
  KK: "Atlasglobal",
  KN: "United Airlines",
  KO: "Komiaviatrans",
  KS: "Penair",
  L6: "Mauritania Airlines",
  KW: "Express Air",
  KY: "Kunming Airlines",
  LI: "LIAT",
  LK: "Lao Skyway",
  LN: "Libyan Airlines",
  M5: "Kenmore Air",
  M8: "SkyJet Airlines",
  M9: "Motor Sich",
  MD: "Air Madagascar",
  MO: "Calm Air",
  MR: "Hunnu Air",
  MW: "Mokulele Airlines",
  N9: "Novair",
  MZ: "Amakusa Airlines",
  NE: "Nesma Airlines",
  NO: "Neos Air",
  NS: "Hebei Airlines",
  NT: "Binter Canarias",
  NU: "Japan Transocean",
  O7: "Orenburzhye Airline",
  NY: "Air Iceland",
  OC: "Air Bridge",
  OI: "Hinterland Aviation",
  OL: "Samoa Airways",
  ON: "Nauru Airlines",
  P0: "Proflight Zambia",
  P2: "Airkenya",
  OQ: "Chongqing Airlines",
  OR: "TUI Nederland",
  P4: "Air Peace",
  P6: "Pascan",
  OW: "Skyward Express",
  OY: "Lineas Aereas",
  PB: "PAL Airlines",
  PE: "'s",
  PI: "Polar Airlines",
  PJ: ". Pierre",
  PL: "Southern Charter",
  PM: "Canaryfly",
  PN: "West Air",
  Q2: "Aviation Services",
  PV: "Barth Commuter",
  Q8: "TAC)",
  PW: "Precision Air",
  PY: "Surinam Airways",
  QB: "Qeshm Air",
  QC: "-Co",
  QL: "LASER Airlines",
  QQ: "Alliance Airlines",
  R2: "Transair",
  R3: "Yakutia Airlines",
  R5: "Jordan Aviation",
  QW: "Qingdao Airlines",
  RC: "Atlantic Airways",
  RL: "Royal Flight",
  RM: "Aircompany Armenia",
  RQ: "Kam Air",
  RT: "UVT Aero",
  S6: "Sunrise Airways",
  RW: "Air Charter",
  S8: "Sounds Air",
  RY: "Jiangxi Air",
  "2B": "Albawings",
  SF: "Tassili Airlines",
  "2G": "Angara Airlines",
  SH: "Sharp Airlines",
  "2J": "Air Burkina",
  "2L": "Helvetic Airways",
  SM: "Air Cairo",
  "2M": "Island Air",
  SP: "Air Acores",
  "2P": "PAL Express",
  SR: "Sundair",
  T5: "Turkmenistan Airlines",
  T6: "AirSWIFT",
  "2T": "TruJet",
  T7: "TWIN JET",
  SZ: "Somon Air",
  "3B": "Cabo Verde",
  TC: "Air Tanzania",
  "3C": "Air Chathams",
  "3E": "Choice One",
  "3H": "Air Inuit",
  TJ: "Tradewind",
  "3J": "Jubba Airways",
  TL: "Airnorth",
  TM: "LAM",
  U4: "Buddha Air",
  "3T": "Tarco",
  TV: "Tibet Airlines",
  TY: "Air Caledonie",
  "4D": "Air Sinai",
  UG: "Tunisair Express",
  "4G": "Gazpromavia",
  UI: "Auric Air",
  UM: "Air Zimbabwe",
  V0: "CONVIASA",
  "4N": "Air North",
  UQ: "Urumqi Air",
  "4P": "Regional Sky",
  V5: "DAP",
  "4W": "s Air",
  UY: "PRIME Charter",
  UZ: "Buraq Air",
  "5F": "FLYONE",
  "5H": "Fly540",
  "5M": "FlyMontserrat",
  "5O": "Airlines France",
  VQ: "NOVOAIR",
  W3: "Arik Air",
  VT: "Air Tahiti",
  "5T": "Canadian North",
  "5U": "TAG Airlines",
  "6I": "Air Alsie",
  "6J": "Solaseed Air",
  WM: "Winair",
  "6O": "Orbest",
  X4: "Air Excursions",
  "6R": "AeroUnion",
  WU: "Jetways Airlines",
  WX: "CityJet",
  "7F": "First Air",
  XG: "SunExpress Deutschland",
  "7G": "Star Flyer",
  "7H": "Ravn Alaska",
  "7J": "Tajik Air",
  XN: "Xpress Air",
  Y2: "Air Century",
  "7P": "Air Panama",
  "7Q": "Elite Airways",
  Y5: "Myanmar Airlines",
  XU: "K)",
  Y8: "Suparna Airlines",
  "7W": "Windrose",
  "7Y": "Yadanarpon Airlines",
  "8B": "TransNusa",
  YC: "Yamal Airlines",
  YE: "Yan Air",
  "8F": "STP Airways",
  "8J": "EcoJet",
  YK: "AviaTraffic Company",
  YN: "Air Creebec",
  "8N": "Regional Air",
  "8P": "Coastal Airlines",
  YT: "Yeti",
  "8T": "Ltd.",
  YU: "EuroAtlantic Airways",
  "8V": "Wright Air",
  Z8: "Amaszonas",
  Z9: "Bek Air",
  "8Z": "Congo Airways",
  ZD: "EWA Air",
  ZF: "AZUR air",
  ZI: "Aigle Azur",
  "9H": "AIR CHANGAN",
  "9I": "Air India",
  "9J": "Dana Air",
  ZM: "Air Manas",
  "9M": "Mountain Air",
  "9N": "Tropic Air",
  "9Q": "Express Airways",
  "9X": "Airways Express"
};

export const lowcostAirlines = [
  "G4",
  "F9",
  "B6",
  "WN",
  "NK",
  "SY",
  "RV",
  "F8",
  "WG",
  "WO",
  "H2",
  "AQ",
  "JD",
  "GY",
  "RY",
  "9C",
  "IX",
  "I5",
  "G8",
  "6E",
  "SG",
  "QG",
  "QZ",
  "JT",
  "IW",
  "DJ",
  "GK",
  "IJ",
  "AK",
  "D7",
  "RS",
  "IT",
  "FD",
  "XJ",
  "SL",
  "G9",
  "FZ",
  "BL",
  "VJ",
  "EC",
  "E2",
  "OE",
  "TO",
  "EW",
  "DE",
  "W6",
  "FR",
  "D8",
  "BV",
  "HV",
  "DY",
  "DU",
  "0B",
  "DP",
  "I2",
  '"VK',
  "V7",
  "VY",
  "LE",
  "DS",
  "U2",
  "BE",
  "LS",
  "DI",
  "RK",
  "W9",
  "JQ",
  "TT"
];

export const legacyAirlines = [
  "AS",
  "AA",
  "DL",
  "HA",
  "UA",
  "ZB",
  "AH",
  "AR",
  "QF",
  "VA",
  "OS",
  "SN",
  "AC",
  "LA",
  "CA",
  "AV",
  "OU",
  "OK",
  "SK",
  "EQ",
  "MS",
  "ET",
  "RC",
  "FJ",
  "AY",
  "AF",
  "LH",
  "A3",
  "CX",
  "FI",
  "AI",
  "GA",
  "EI",
  "IR",
  "IA",
  "LY",
  "AZ",
  "JL",
  "RJ",
  "KC",
  "KQ",
  "KU",
  "QV",
  "BT",
  "LG",
  "MH",
  "AM",
  "KL",
  "PK",
  "CM",
  "PR",
  "LO",
  "TP",
  "QR",
  "RO",
  "SV",
  "JU",
  "SQ",
  "SA",
  "KE",
  "IB",
  "LX",
  "CI",
  "TG",
  "TK",
  "PS",
  "EY",
  "EK",
  "BA",
  "HY",
  "V0",
  "VN"
];
