const cityThumbnails = {
  SEL: ["SEL2.jpg", "SEL.jpg"],
  CLT: ["CLT.jpg"],
  DUB: ["DUB.jpg"],
  IST: ["IST.jpg", "IST2.jpg"],
  MOW: ["MOW.jpg", "MOW2.jpg"],
  WAS: ["WAS2.jpg", "WAS.jpg", "WAS3.jpg"],
  SPK: ["SPK.jpg"],
  HKG: ["HKG2.jpg", "HKG.jpg", "HKG3.jpg"],
  TPA: ["TPA.jpg"],
  FRA: ["FRA.jpg"],
  LAX: ["LAX3.jpg", "LAX4.jpg", "LAX2.jpg", "LAX.jpg"],
  SYD: ["SYD.jpg"],
  PHL: ["PHL.jpg", "PHL2.jpg"],
  JKT: ["JKT.jpg"],
  BNE: ["BNE.jpg"],
  CAN: ["CAN.jpg"],
  HOU: ["HOU.jpg"],
  LIS: ["LIS.jpg"],
  SMP: ["SMP.jpg"],
  BSB: ["BSB.jpg"],
  BOM: ["BOM.jpg"],
  CTU: ["CTU.jpg"],
  AKL: ["AKL1.jpg"],
  BOS: ["BOS3.jpg", "BOS2.jpg", "BOS.jpg"],
  AMS: ["AMS1.jpg", "AMS2.jpg"],
  OSL: ["OSL2.jpg", "OSL.jpg"],
  MIA: ["MIA.jpg"],
  SLC: ["SLC.jpg"],
  LAS: ["LAS.jpg"],
  BER: ["BER.jpg"],
  YTO: ["YTO.jpg"],
  BWI: ["BWI1.jpg"],
  JED: ["JED.jpg"],
  FUK: ["FUK.jpg"],
  TYO: ["TYO.jpg", "TYO2.jpg", "TYO3.jpg"],
  SAN: ["SAN2.jpg", "SAN.jpg"],
  MAN: ["MAN.jpg"],
  FLL: ["FLL.jpg"],
  CHI: ["CHI.jpg", "CHI3.jpg", "CHI2.jpg"],
  HEL: ["HEL.jpg"],
  PHX: ["PHX.jpg"],
  DEL: ["DEL.jpg"],
  MEL: ["MEL2.jpg", "MEL.jpg"],
  DXB: ["DXB.jpg"],
  ORL: ["ORL.jpg"],
  KUL: ["KUL.jpg"],
  MSP: ["MSP.jpg"],
  CPT: ["CPT.jpg", "CPT2.jpg"],
  SFO: ["SFO.jpg", "SFO2.jpg"],
  BKK: ["BKK.jpg", "BKK2.jpg", "BKK3.jpg"],
  CPH: ["CPH.jpg"],
  SHA: ["SHA2.jpg", "SHA.jpg"],
  MNL: ["MNL.jpg"],
  HGH: ["HGH.jpg"],
  ROM: ["ROM2.jpg", "ROM.jpg"],
  Doha: ["Doha.jpg"],
  AYT: ["AYT1.jpg"],
  LON: ["LON2.jpg", "LON.jpg"],
  ZRH: ["ZRH.jpg"],
  CJU: ["CJU.jpg"],
  BJS: ["BJS3.jpg", "BJS2.jpg", "BJS.jpg"],
  DTT: ["DTT.jpg"],
  SIN: ["SIN3.jpg", "SIN.jpg", "SIN2.jpg"],
  JNB: ["JNB.jpg"],
  NYC: ["NYC.jpg", "NYC2.jpg", "NYC3.jpg", "NYC4.jpg"],
  KMG: ["KMG.jpg"],
  SZX: ["SZX.jpg"],
  MEX: ["MEX.jpg"],
  VIE: ["VIE.jpg"],
  YVR: ["YVR.jpg"],
  MAD: ["MAD.jpg", "MAD2.jpg"],
  RUH: ["RUH.jpg"],
  ATH: ["ATH1.jpg"],
  MIL: ["MIL.jpg"],
  SEA: ["SEA.jpg"],
  BOG: ["BOG.jpg"],
  ATL: ["ATL1.jpg"],
  BRU: ["BRU.jpg"],
  RIO: ["RIO.jpg"],
  DEN: ["DEN2.jpg", "DEN.jpg"],
  SAO: ["SAO.jpg"],
  PMI: ["PMI.jpg"],
  DFW: ["DFW.jpg"],
  TPE: ["TPE.jpg"],
  DUS: ["DUS.jpg"],
  BCN: ["BCN.jpg"],
  MUC: ["MUC.jpg"],
  PAR: ["PAR.jpg"]
};

const airportMetropolitans = {
  BKK: "BKK",
  DMK: "BKK",
  PEK: "BJS",
  NAY: "BJS",
  KIX: "OSA",
  ITM: "OSA",
  UKB: "OSA",
  CTS: "SPK",
  OKD: "SPK",
  ICN: "SEL",
  GMP: "SEL",
  SHA: "SHA",
  PVG: "SHA",
  NRT: "TYO",
  HND: "TYO",
  CGK: "JKT",
  HLP: "JKT",
  BER: "BER",
  TXL: "BER",
  SXF: "BER",
  OTP: "BUH",
  BBU: "BUH",
  BRU: "BRU",
  CRL: "BRU",
  BQH: "LON",
  LCY: "LON",
  LGW: "LON",
  LTN: "LON",
  LHR: "LON",
  SEN: "LON",
  STN: "LON",
  BGY: "MIL",
  MXP: "MIL",
  LIN: "MIL",
  PMF: "MIL",
  SVO: "MOW",
  DME: "MOW",
  VKO: "MOW",
  BKA: "MOW",
  OSL: "OSL",
  TRF: "OSL",
  RYG: "OSL",
  CDG: "PAR",
  ORY: "PAR",
  LBG: "PAR",
  KEF: "REK",
  RKV: "REK",
  FCO: "ROM",
  CIA: "ROM",
  ARN: "STO",
  NYO: "STO",
  BMA: "STO",
  VST: "STO",
  TFN: "TCI",
  TFS: "TCI",
  ORD: "CHI",
  MDW: "CHI",
  RFD: "CHI",
  DAL: "DFW",
  DFW: "DFW",
  DTW: "DTT",
  DET: "DTT",
  YIP: "DTT",
  YEG: "YEA",
  LAX: "LAX",
  MIA: "QMI",
  FLL: "QMI",
  PBI: "QMI",
  YUL: "YMQ",
  YMY: "YMQ",
  JFK: "NYC",
  EWR: "NYC",
  LGA: "NYC",
  HPN: "NYC",
  YYZ: "YTO",
  YTZ: "YTO",
  YKF: "YTO",
  IAD: "WAS",
  DCA: "WAS",
  BWI: "WAS",
  CNF: "BHZ",
  PLU: "BHZ",
  EZE: "BUE",
  AEP: "BUE",
  GIG: "RIO",
  SDU: "RIO",
  GRU: "SAO",
  CGH: "SAO",
  VCP: "SAO"
};

const defaultThumbnails = ["default.jpg", "default2.jpg"];

export function getCityThumbnail(code) {
  let lookupCode;
  if (code in airportMetropolitans) {
    lookupCode = airportMetropolitans[code];
  } else {
    lookupCode = code;
  }
  if (lookupCode in cityThumbnails) {
    const options = cityThumbnails[lookupCode];
    const fileName = options[Math.floor(Math.random() * options.length)];
    return `${process.env.BASE_URL}images/cities/${fileName}`;
  } else {
    const fileName =
      defaultThumbnails[Math.floor(Math.random() * defaultThumbnails.length)];
    return `${process.env.BASE_URL}images/${fileName}`;
  }
}
